name: Deploy Project
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
env:
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_SSH_KEY: ${{ secrets.SSH_KEY }}
  TF_VAR_SSH_KEY_PUB: ${{ secrets.SSH_KEY_PUB }}


jobs:
  create-tfstate-bucket:
    uses: ./.github/workflows/create-tfstate-bucket.yml
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        
  deploy-project:
    needs: create-tfstate-bucket 
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Get repo name
      run: |
        echo "TF_VAR_REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
        echo "TF_VAR_FULL_REPO_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
        echo "${GITHUB_REPOSITORY}"
        aws ssm get-parameter --name "/aws/service/canonical/ubuntu/server/noble/stable/current/amd64/hvm/ebs-gp3/ami-id" --region ${{ secrets.AWS_REGION }}


    - name: Create provider.tf and pass variables dynamicaly
      run: |
        cat <<EOF > ./provider.tf
        
        terraform {
          required_providers {
            aws = {
              source  = "hashicorp/aws"
              # version = "5.99.0"
              version = "6.0.0"

            }
          }

          backend "s3" {
            bucket         = "${{ env.TF_VAR_REPO_NAME }}-terraform-tfstate"
            key            = "terraform.tfstate"
            # dynamodb_table = "main-tfstate"
            region         = "${{ secrets.AWS_REGION }}"
          }
        }

        provider "aws" {
          region = "${{ secrets.AWS_REGION }}"
        }
        EOF
        cat ./provider.tf
        
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform validate
      id: validate
      run: terraform validate

    - name: Terraform plan
      id: plan
      run: terraform plan -out=plan.tfplan
      continue-on-error: true

    - name: Terraform apply
      id: apply
      run: terraform apply plan.tfplan
